### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by morten-nielsen** [tomoyukim/vscode-mermaid-editor#24]
Is is possible to adjust the image quality/dpi on jpg, the output images are sometimes really poor.

**Comment by Pindar777** [comment]
@tomoyukim The best output option seems to me svg. In order to get high resolution picture other tools can be used later on. However, the svg-export is missing the desired background-color. Hence, it would ne nice if yout package could handle this by augmenting the first style-css statement (at the moment only containg the width-property)  the parameter specified by  `%% @backgroundColor{rgb(40, 44, 52)}`:

`style="background-color: red; max-width: 879px;"`

**Comment by tomoyukim** [comment]
Hello, I introduced a new config to set the image quality and fixed to set background color for SVG in v0.12.0.
