### ISSUE TITLE
[Question] Dark mode / theme

### ISSUE THREAD

**Issue by lonix1** [tomoyukim/vscode-mermaid-editor#51]
I read the docs and a number of other issues, but can't find relevant info.

What must I do to enable dark mode?

I did this:
- added file `path/to/config.json` which contains: `{ "theme": "dark" }`
- added to my settings: `"mermaid-editor.preview.defaultMermaidConfig": "path/to/config.json"`

That shows a class diagram with black classes, but on white background. Not really a "dark mode" theme.

What is the correct way to do this?

**Comment by tomoyukim** [comment]
Hello,

You should set the background color by yourself because the config which is defined by mermaid.js only affects the elements in the graph. This extension provides an original way to support this setting with an attribute. Please refer to [this](https://github.com/tomoyukim/vscode-mermaid-editor#backgroundcolorcolor) document and set your favorite color. Thank you!

**Comment by lonix1** [comment]
Thanks!
