### ISSUE TITLE
Preserve scroll position between reloads

### ISSUE THREAD

**Issue by juancri** [tomoyukim/vscode-mermaid-editor#6]
When previewing a long graph, the scroll position is retested every time a change is made to the code and the preview is reloaded. It would be nice to preserve the scroll position so users don't need to scroll manually every time.

**Comment by tomoyukim** [comment]
Thank you for good advise for user experience and I totally understand your suggestion. Unfortunately, I couldn't find a solution to reset scroll position of the graph for now because mermaid.js uses D3.js internally and I've not found the way to listen or get the latest position in it. I'll check and consider the way to approach this issue continuously. Thank you for your support again.

**Comment by juancri** [comment]
Thank you. I'll try to investigate and will post any updates here.

**Comment by tomoyukim** [comment]
Hi @juancri, I finally support preserving scroll position during edit. Please check it out if you have time. Unfortunately, the position will be reset when syntax error. I think I'll try to improve the behavior in next step. Thank you.
